admincase/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import autenticarse
from django.conf import settings
from admincase import views

urlpatterns = [
    url(r'^$', autenticarse),
    url(r'^autenticar_usuario/', views.autenticar_usuario),
    # url(r'^reset_password/', views.reset_password, name='rest_password'),
    url(r'^ayuda/', views.ayuda),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^clientes/', include('apps.clientes.urls', namespace='clientes')),
    url(r'^contactos/', include('apps.contactos.urls', namespace='contactos')),
    url(r'^domicilios/', include('apps.domicilios.urls',
                                 namespace='domicilios')),
    url(r'^inicio/', views.inicio, name='inicio'),
    url(r'^internos/', views.internos, name='internos'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, }),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),
    url(r'^salir/', views.salir),
    url(r'^tramites/', include('apps.tramites.urls', namespace='tramites')),
    url(r'^entidades/', include('apps.complementos.organigrama.urls',
                                namespace='entidades')),

    url(r'^reset_password/', include('password_reset.urls')),
]

apps/tramites/urls.py
from django.conf.urls import url
# from apps.tramites import helpers

from .views import * #(TramiteListView, TramiteCreate, TramiteUpdate,
                    # TramiteClienteListView, TramiteDelete,
                    # TipoTramiteListView) #, TramiteEntidadCreate)

from . import helpers


urlpatterns = [
    url(r'^listado/$', TramiteListView.as_view(), name='tramite_list'),
    url(r'^listado/(?P<pk>[0-9]+)/$', TramiteClienteListView.as_view(),
        name='tramite_cliente_list'),
    url(r'^alta/$', TramiteCreate.as_view(), name='tramite_add'),
    url(r'^alta/(?P<pk>[0-9]+)/$', TramiteCreate.as_view(), name='tramite_add'),
    url(r'^modi/(?P<pk>[0-9]+)/$', TramiteUpdate.as_view(),
        name='tramite_update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', TramiteDelete.as_view(),
        name='tramite_delete'),
    url(r'^get_requisitos_tipo_tramite/$', helpers.get_requisitos_tipo_tramite,
        name='get_requisitos_tipo_tramite'),
    url(r'^tipo/listado/$', TipoTramiteListView.as_view(),
        name='tipo_tramite_list'),
    url(r'^tipo/alta/$', TipoTramiteCreate.as_view(), name='tramite_add'),
    url(r'^tipo/alta/(?P<pk>[0-9]+)/$', TipoTramiteCreate.as_view(), name='tramite_add'),
    url(r'^tipo/modi/(?P<pk>[0-9]+)/$', TipoTramiteUpdate.as_view(),
        name='tramite_update'),
    url(r'^tipo/delete/(?P<pk>[0-9]+)/$', TipoTramiteDelete.as_view(),
        name='tramite_delete'),
]

apps/tramites/models.py
from datetime import datetime
from django.db import models

from apps.complementos.organigrama.models import Entidad
from apps.clientes.models import Cliente


class TipoTramite(models.Model):
    descripcion = models.CharField(max_length=50)
    entidad = models.ForeignKey(Entidad, null=True, blank=True)

    def __str__(self):
        return self.descripcion + ' - ' + str(self.entidad)

    class Meta:
        ordering = ['entidad']
        verbose_name_plural = "Tipos de Tramite"


class Requisito(models.Model):
    descripcion = models.CharField(max_length=50, null=True, blank=True)
    valor = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.descripcion

    class Meta:
        verbose_name_plural = "Requisitos"


class RequisitoTipoTramite(models.Model):
    tipo_tramite = models.ForeignKey(TipoTramite, null=False, blank=True)
    requisito = models.ForeignKey(Requisito, null=False, blank=True)
    estado = models.BooleanField(default=False)

    def __str__(self):
        return str(self.tipo_tramite) + '-' + str(self.requisito) + '-' + str(self.estado)

    class Meta:
        verbose_name_plural = "Requisitos del Tipo de Tramite"


class Tramite(models.Model):
    cliente = models.ForeignKey(Cliente, null=True, blank=True)
    tipo = models.ForeignKey(TipoTramite, null=True, blank=True)
    fecha_alta = models.DateTimeField(
        default=datetime.now, null=True, blank=True)
    fecha_turno = models.DateField(null=True, blank=True)
    fecha_alarma = models.DateField(null=True, blank=True)
    fecha_fin = models.DateField(null=True, blank=True)
    estado = models.BooleanField(default=False, blank=True)
    observaciones = models.TextField(max_length=None, null=True, blank=True)

    def __str__(self):
        return str(self.tipo)

    class Meta:
        ordering = ['-fecha_alta']
        verbose_name_plural = "Tramites"


class RequisitoTramite(models.Model):
    tramite = models.ForeignKey(Tramite, null=False, blank=True)
    requisito = models.ForeignKey(Requisito, null=False, blank=True)
    presentado = models.BooleanField(default=False)

    def __str__(self):
        return str(self.tramite) + '-' + str(self.requisito) + '-' + \
            str(self.presentado)

    class Meta:
        verbose_name_plural = "Requisitos Requeridos del Tramite"

apps/tramites/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext

from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.clientes.models import Cliente
# from apps.complementos.organigrama.models import Entidad
from apps.tramites.models import (Tramite, TipoTramite, RequisitoTramite,
                                  Requisito, RequisitoTipoTramite)

from .forms import TramiteForm, TipoTramiteForm


class TramiteListView(ListView):
    model = Tramite
    paginate_by = 10

    def get_queryset(self):

        query = super(TramiteListView, self).get_queryset()

        return query


class TramiteCreate(CreateView):
    model = Tramite
    form_class = TramiteForm

    def get(self, request, *args, **kwargs):
        form = TramiteForm()

        cliente = Cliente.objects.get(pk=kwargs['pk'])

        return render_to_response(
            'tramites/tramite_form.html',
            {
                'form': form,
                'cliente': cliente
            },
            context_instance=RequestContext(request)
        )

    def post(self, request, *args, **kwargs):

        form = TramiteForm(data=self.request.POST)

        cliente = Cliente.objects.get(pk=int(self.request.POST['cliente']))

        if form.is_valid():
            tramite = form.save()

            requisitos_tramite = self.request.POST['requisitos_presentados']

            if requisitos_tramite:
                parametros = requisitos_tramite.split("|")

                for item in parametros:
                    print(item)
                    requisito_parametro = item.split("#")

                    requisito = Requisito.objects.get(
                        valor=requisito_parametro[0])

                    presentado = (False, True)[requisito_parametro[1] == '1']

                    RequisitoTramite.objects.create(
                        tramite=tramite,
                        requisito=requisito,
                        presentado=presentado
                    )

            messages.add_message(
                request, messages.SUCCESS, 'EL TRAMITE SE HA CREADO CON EXITO')

            return HttpResponseRedirect('/tramites/modi/' + str(tramite.id))

        messages.add_message(
            request, messages.ERROR, 'EL FORMULARIO CONTIENE ERRORES')

        return render_to_response(
            'tramites/tramite_form.html',
            {
                'form': form,
                'cliente': cliente
            },
            context_instance=RequestContext(request)
        )


class TramiteUpdate(UpdateView):
    model = Tramite
    form_class = TramiteForm

    def get(self, request, *args, **kwargs):
        tramite = Tramite.objects.get(pk=kwargs['pk'])
        cliente = Cliente.objects.get(pk=tramite.cliente.id)
        requisitos_tramite = tramite.requisitotramite_set.all()

        form = TramiteForm(instance=tramite)

        return render_to_response(
            'tramites/tramite_form.html',
            {
                'form': form,
                'cliente': cliente,
                'requisitos': requisitos_tramite
            },
            context_instance=RequestContext(request)
        )

    def post(self, request, *args, **kwargs):

        tramite = Tramite.objects.get(pk=kwargs['pk'])

        cliente = Cliente.objects.get(pk=tramite.cliente.id)

        requisitos_tramite = tramite.requisitotramite_set.all()

        form = TramiteForm(self.request.POST, instance=tramite)

        if form.is_valid():
            form.save()

            requisitos = self.request.POST['requisitos_presentados']

            if requisitos:
                parametros = requisitos.split("|")

                # print(requisitos)

                for item in parametros:
                    requisito_parametro = item.split("#")
                    requisito = RequisitoTramite.objects.get(
                        requisito__valor=requisito_parametro[0])
                    presentado = (False, True)[requisito_parametro[1] == '1']
                    requisito.presentado = presentado
                    requisito.save()

            messages.add_message(
                request, messages.SUCCESS,
                'EL TRAMITE SE HA ACTUALIZADO CON EXITO')

            return HttpResponseRedirect(self.get_success_url())

        messages.add_message(
            request, messages.ERROR, 'EL FORMULARIO CONTIENE ERRORES')

        return render_to_response(
            'tramites/tramite_form.html',
            {
                'form': form,
                'tramite': tramite,
                'cliente': cliente,
                'requisitos': requisitos_tramite
            },
            context_instance=RequestContext(request)
        )

    def get_success_url(self):
        return self.request.get_full_path()


class TramiteDelete(DeleteView):

    model = Tramite
    success_message = 'El trámite fue eliminado con éxito'

    def get_success_url(self):
        tramite = Tramite.objects.get(pk=self.kwargs['pk'])
        cliente = Cliente.objects.get(pk=tramite.cliente.id)

        return '/tramites/listado/' + str(cliente.id)


class TramiteClienteListView(ListView):
    model = Tramite
    paginate_by = 10

    def get(self, request, *args, **kwargs):

        cliente = Cliente.objects.get(pk=kwargs['pk'])

        tramite_cliente = Tramite.objects.filter(cliente__id=cliente.id)

        return render_to_response(
            'tramites/tramite_cliente_list.html',
            {
                'cliente': cliente,
                'tramite_cliente': tramite_cliente
            },
            context_instance=RequestContext(request)
        )


class TipoTramiteListView(ListView):
    model = TipoTramite
    paginate_by = 10

    def get_queryset(self):

        query = super(TipoTramiteListView, self).get_queryset()

        return query


class TipoTramiteCreate(CreateView):
    model = TipoTramite
    form_class = TipoTramiteForm

    def get(self, request, *args, **kwargs):

        form = TipoTramiteForm()

        requisitos = Requisito.objects.all()

        return render_to_response(
            'tramites/tipotramite_form.html',
            {
                'form': form,
                'requisitos': requisitos
            },
            context_instance=RequestContext(request)
        )

    def post(self, request, *args, **kwargs):

        form = TipoTramiteForm(data=self.request.POST)

        requisitos = Requisito.objects.all()

        if form.is_valid():
            tipo_tramite = form.save()

            requisitos_tramite = self.request.POST['requisitos_presentados']

            if requisitos_tramite:
                parametros = requisitos_tramite.split("|")

                for item in parametros:
                    requisito_necesario = item.split("#")

                    requisito = Requisito.objects.get(
                        valor=requisito_necesario[0])

                    es_requisito = (False, True)[requisito_necesario[1] == '1']

                    # if es_requisito:
                    RequisitoTipoTramite.objects.create(
                        tipo_tramite=tipo_tramite,
                        requisito=requisito,
                        estado=es_requisito
                    )

            messages.add_message(
                request, messages.SUCCESS,
                'EL TIPO DE TRAMITE SE HA CREADO CON EXITO')

            return HttpResponseRedirect('/tramites/tipo/modi/' +
                                        str(tipo_tramite.id))

        messages.add_message(
            request, messages.ERROR, 'EL FORMULARIO CONTIENE ERRORES')

        return render_to_response(
            'tramites/tipotramite_form.html',
            {
                'form': form,
                'requisitos': requisitos
            },
            context_instance=RequestContext(request)
        )


class TipoTramiteUpdate(UpdateView):
    model = TipoTramite
    form_class = TipoTramiteForm

    def get(self, request, *args, **kwargs):

        tipo_tramite = TipoTramite.objects.get(pk=kwargs['pk'])
        form = TipoTramiteForm(instance=tipo_tramite)

        requisitos = tipo_tramite.requisitotipotramite_set.all()

        return render_to_response(
            'tramites/tipotramite_form.html',
            {
                'form': form,
                'requisitos': requisitos
            },
            context_instance=RequestContext(request)
        )

    def post(self, request, *args, **kwargs):

        tipo_tramite = TipoTramite.objects.get(pk=kwargs['pk'])
        form = TipoTramiteForm(data=self.request.POST, instance=tipo_tramite)

        requisitos = tipo_tramite.requisitotipotramite_set.all()

        if form.is_valid():
            tipo_tramite = form.save()

            requisitos_tramite = self.request.POST['requisitos_presentados']

            if requisitos_tramite:
                parametros = requisitos_tramite.split("|")

                for item in parametros:
                    requisito_necesario = item.split("#")
                    requisito_tramite = RequisitoTipoTramite.objects.get(
                        tipo_tramite__id=tipo_tramite.id,
                        requisito__valor=requisito_necesario[0])
                    es_necesario = (False, True)[requisito_necesario[1] == '1']
                    requisito_tramite.estado = es_necesario
                    requisito_tramite.save()


            messages.add_message(
                request, messages.SUCCESS,
                'EL TIPO DE TRAMITE SE HA MODIFICADO  CON EXITO')

            return HttpResponseRedirect('/tramites/tipo/modi/' +
                                        str(tipo_tramite.id))

        messages.add_message(
            request, messages.ERROR, 'EL FORMULARIO CONTIENE ERRORES')

        return render_to_response(
            'tramites/tipotramite_form.html',

templates/tramites/tipotramite_confirm_delete.html
{% extends 'arbol_item.html' %}
{% block content %}

    <div class="title_right" style="background-color:#ccc">
        <div class="x_title">
            <a href='/'><strong>INICIO</strong></a> --
            <a href='/tramites/tipo/listado'><strong>LISTADO TIPO TRAMITES</strong></a> --
            <strong>TIPO TRAMITE</strong>
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="row">

        <form method="post"> {% csrf_token %}
        <div class="col-md-12 col-sm-12 col-xs-12 animated fadeInDown">
            <div class="x_panel">
                <div class="x_title">
                    <h2>ELIMINAR TIPO DE TRAMITE</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="col-sm-12">
                        <h2 class="brief"><i> Está seguro de eliminar el tipo de tramite?</i></h2>
                        <ul class="list-unstyled">
                            {% if object.descripcion %}
                            <li> <label>Tipo de Tramite</label> : {{ object.descripcion }} </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="x_panel">
                <div class="x_content">
                    <div class="col-xs-2"></div>
                    <div class="col-xs-5">
                        <div class="col-xs-3 col-sm-3 emphasis">
                            <a class="btn btn-success btn-xl" href="/tramites/tipo/modi/{{ object.id }}" type="button"> <i class="fa fa-arrow-left"></i> Cancelar</a>
                        </div>
                        <div class="col-xs-3 col-sm-3 emphasis">
                            <button class="btn btn-danger btn-xl" type="submit" ><i class="fa fa-trash"></i> Eliminar </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </form>
    </div>
{% endblock %}

templates/tramites/tipotramite_form.html
{% extends 'arbol_item.html' %}
{% load staticfiles %}

{% block content %}

<div class="title_right" style="background-color:#ccc">
    <div class="x_title">
        <a href='/'><strong>INICIO</strong></a> --
        <a href='/tramites/tipo/listado'><strong>LISTADO TIPO TRAMITES</strong></a> --
        <strong>TIPO TRAMITE</strong>
    </div>
</div>
{% if messages %}
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="alert alert-success" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
</div>
{% endif %}
<div class="clearfix"></div>
<form id="frm" method="post" data-parsley-validate class="form-horizontal form-label-left">{% csrf_token %}
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><strong>DATOS TIPO DE TRAMITE</strong></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-8 col-sm-8 col-xs-12">
                    {{ form }}
                </div>
            </div>
        </div>
        <div class="x_panel">
            <div class="x_content">
                <div class="form-group">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <button type="button" id="btnEliminar" class="btn btn-danger">Eliminar</button>
                        <button type="button" id="btnCancelar" class="btn btn-primary">Cancelar</button>
                        <button type="button" id="btnGuardar" class="btn btn-success">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><strong>REQUISITOS</strong> (Seleccione los que son necesarios)</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <input type="hidden" id="id_requisitos_presentados" name="requisitos_presentados" value=""/>
                <div  id="check_requisitos">
                    <ul class="to_do">
                        {% for requisito in requisitos %}
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <li><label><p><input type='checkbox' class='flat' id="{{ requisito.id }}" name="{{ requisito.valor }}{{ requisito.requisito.valor }}" value='0' {% if requisito.estado %} checked {% endif %}> {{ requisito.requisito }} {{ requisito.descripcion }} </p></label></li>
                            </div>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

<script>
    var frm = document.getElementById('frm');
    var requisito = "";

    $(document).ready(function(){
        $('#id_descripcion').attr('placeholder', 'Introduzca un nombre...');
    });

    $('#btnGuardar').click(function(){

        $('div#check_requisitos input[type=checkbox]').each(function() {
            if ($(this).is(":checked")) {
                requisito += $(this).attr('name') + '#1|';
            } else {
                requisito += $(this).attr('name') + '#0|';
            }
        });

        $('#id_requisitos_presentados').val(requisito.slice(0,-1));

        frm.submit();
    });

    $('#btnCancelar').click(function(){

        location.href = '/tramites/tipo/listado/';
    });

    $('#btnEliminar').click(function(){

        location.href = '/tramites/tipo/delete/{{ form.instance.id }}';
    });


</script>



{% endblock %}

templates/tramites/tramite_form.html
{% extends 'arbol_item.html' %}
{% load staticfiles %}

{% block content %}

<div class="title_right" style="background-color:#ccc">
    <div class="x_title">
        <a href='/'><strong>INICIO</strong></a> --
        <a href='/clientes/listado'><strong>LISTA DE CLIENTES</strong></a> --
        <a href='/clientes/modi/{{ cliente.id }}'><strong>DATOS DEL CLIENTE</strong></a> --
        <a href='/contactos/alta/{{ cliente.id }}'><strong>CONTACTO</strong></a> --
        <a href='/tramites/listado/{{ cliente.id }}'><strong>HISTORIAL DE TRAMITES</strong></a> --
        <strong>TRAMITE</strong>
    </div>
</div>
{% if messages %}
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="alert alert-success" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
</div>
{% endif %}
<div class="clearfix"></div>
<form id="frm" method="post" data-parsley-validate class="form-horizontal form-label-left">{% csrf_token %}
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><strong>DETALLE DEL TRAMITE</strong></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <input id="id_cliente" name="cliente" type="hidden" value="{{ cliente.id }}" />

                <div class="form-group">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <label for="" class="col-md-12 col-sm-12 col-xs-12">Tipo de Trámite</label>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            {{ form.tipo }}
                        </div>{{ form.tipo.errors }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="col-md-6 col-sm-6 col-xs-12">
                           <label for="fullname" class="col-md-12 col-sm-12 col-xs-12">Fecha de Turno (dd/mm/aaaa)</label>
                            <div class="input-group input-append date col-md-12 col-sm-12 col-xs-12" id="dateRangePicker">
                                {{ form.fecha_turno }}
                                <span class="input-group-addon add-on"><span class="fa fa-calendar has-feedback-right"></span></span>
                            </div>{{ form.fecha_turno.errors }}
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                           <label for="fullname" class="col-md-12 col-sm-12 col-xs-12">Fecha Alarma (dd/mm/aaaa)</label>
                             <div class="input-group input-append date col-md-12 col-sm-12 col-xs-12" id="dateRangePicker2">
                                {{ form.fecha_alarma }}
                                <span class="input-group-addon add-on"><span class="fa fa-calendar has-feedback-right"></span></span>
                            </div>{{ form.fecha_alarma.errors }}
                        </div>
                    </div>
                </div>
                <!--div class="form-group">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <label for="id_estado">Estado:</label>
                            {{ form.estado }}
                        </div>{{ form.estado.errors }}
                    </div>
                </div-->
                <div class="form-group">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <label for="id_observaciones"  class="col-md-12 col-sm-12 col-xs-12">Observaciones:</label>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            {{ form.observaciones }}
                        </div>{{ form.observaciones.errors }}
                    </div>
                </div>
                <br>
                <div class="form-group">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <button type="button" id="btnEliminar" class="btn btn-danger">Eliminar</button>
                            <button type="button" id="btnCancelar" class="btn btn-primary">Cancelar</button>
                            <button type="button" id="btnGuardar" class="btn btn-success">Guardar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><strong>REQUISITOS NECESARIOS </strong></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <input type="hidden" id="id_requisitos_presentados" name="requisitos_presentados" value=""/>
                <div  id="check_requisitos">
                    <ul class="to_do">
                    {% for requisito in requisitos %}
                        <li>
                            <label><p><input type='checkbox' class='flat' id="{{ requisito.requisito.id }}" name="{{ requisito.requisito.valor }}" value='0' {% if requisito.presentado %} checked {% endif %}> {{ requisito.requisito }} </p></label>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

<script>

    $(document).ready(function(){

        $("#id_fecha_turno").attr("placeholder","__/__/____");
        $("#id_fecha_turno").mask("99/99/9999");

        $("#id_fecha_alarma").attr("placeholder","__/__/____");
        $("#id_fecha_alarma").mask("99/99/9999");

        //$('.errorlist').css('padding', '15px');
        //$('.errorlist').css('margin-top', '10px');
        //$('.errorlist').css('margin-bottom', '10px');
        $('.errorlist').css('border', '1px solid transparent');
        $('.errorlist').css('border-radius', '4px');
        $('.errorlist').css('color', '#a94442');
        $('.errorlist').css('background', '#f2dede');
        $('.errorlist').css('border-color', '#ebccd1');
        $('.errorlist').css('font-size', '0.9em');
        $('.errorlist').css('list-style-type', 'none');
        //$('.errorlist').css('text-align', 'center');
    });

    var frm = document.getElementById('frm');
    var requisito = "";

    $("#id_tipo").change(function() {

        if('{{ form.instance.id }}' != 'None'){
            alert("No puede modificar el tipo de tramite, debe eliminar y crear un tramite nuevo!");
            $("#id_tipo option[value="+ {{ form.tipo.value }} +"]").prop('selected', true);
            return;
        }

        $("#check_requisitos").html("");

        $.ajax({
            url:"/tramites/get_requisitos_tipo_tramite/",
            cache: false,
            type: "GET",
            data: {id_tipo: $("#id_tipo").val()},
            success: function(data) {

                for (item in data) {
                    var check = "<label><input type='checkbox' class='flat' id='" +
                            data[item].id + "' name='" + data[item].valor +
                            "' value='0'> " + data[item].descripcion + "</label><br>";
                    $("#check_requisitos").append(check);
                }

            }
        });

    });

    $('#btnGuardar').click(function(){

        $('div#check_requisitos input[type=checkbox]').each(function() {
            if ($(this).is(":checked")) {
                requisito += $(this).attr('name') + '#1|';
            } else {
                requisito += $(this).attr('name') + '#0|';
            }
        });

        $('#id_requisitos_presentados').val(requisito.slice(0,-1));

        frm.submit();
    });

    $('#btnCancelar').click(function(){

        location.href = '/tramites/listado/{{ cliente.id }}';
    });

    $('#btnEliminar').click(function(){

        location.href = '/tramites/delete/{{ form.instance.id }}';
    });


</script>



{% endblock %}