admincase/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import autenticarse
from django.conf import settings
from admincase import views

urlpatterns = [
    url(r'^$', autenticarse),
    url(r'^autenticar_usuario/', views.autenticar_usuario),
    # url(r'^reset_password/', views.reset_password, name='rest_password'),
    url(r'^ayuda/', views.ayuda),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^clientes/', include('apps.clientes.urls', namespace='clientes')),
    url(r'^contactos/', include('apps.contactos.urls', namespace='contactos')),
    url(r'^domicilios/', include('apps.domicilios.urls',
                                 namespace='domicilios')),
    url(r'^inicio/', views.inicio, name='inicio'),
    url(r'^internos/', views.internos, name='internos'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, }),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),
    url(r'^salir/', views.salir),
    url(r'^tramites/', include('apps.tramites.urls', namespace='tramites')),
    url(r'^entidades/', include('apps.complementos.organigrama.urls',
                                namespace='entidades')),

    url(r'^reset_password/', include('password_reset.urls')),
]

apps/complementos/organigrama/urls.py
from django.conf.urls import patterns, url

from .views import (EntidadListView, EntidadCreate, EntidadUpdate,
                    EntidadDelete)


urlpatterns = patterns('',
    url(r'^listado/$', EntidadListView.as_view(), name='entidad_listado'),
    url(r'^alta/$', EntidadCreate.as_view(), name='entidad_alta'),
    url(r'^modi/(?P<pk>[0-9]+)/$', EntidadUpdate.as_view(),
        name='entidad_update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', EntidadDelete.as_view(),
        name='entidad_delete'),
)

apps/complementos/organigrama/models.py
import os
from django.db import models


class Profesion(models.Model):
    nombre = models.CharField(max_length=70, unique=True)
    #audit_log = AuditLog()

    def __str__(self):
        return self.nombre.title()

    class Meta:
        verbose_name_plural = "Profesiones"
        ordering = ['nombre']


def _generar_ruta_imagen(instance, filename):
        # El primer paso es extraer la extension de la imagen del
        # archivo original
        extension = os.path.splitext(filename)[1][1:]

        # Generamos la ruta relativa a MEDIA_ROOT donde almacenar
        # el archivo, usando la fecha actual (año/mes)
        # ruta = os.path.join('foto_persona', date.today().strftime("%Y/%m"))
        # ruta = os.path.join('foto_persona')
        ruta = 'tramites_entidades'

        # Generamos el nombre del archivo con un identificador
        # aleatorio, y la extension del archivo original.
        nombre_archivo = '{}.{}'.format(instance.nombre, extension)

        # Devolvermos la ruta completa
        return os.path.join(ruta, nombre_archivo)


class Entidad(models.Model):
    nombre = models.CharField(max_length=50, unique=True, blank=False)
    valor = models.CharField(max_length=50, unique=True, null=True, blank=False)
    imagen = models.ImageField(
        upload_to=_generar_ruta_imagen, blank=True, null=True)

    def __str__(self):
        return self.nombre.title()

    class Meta:
        verbose_name_plural = "Entidades"
        ordering = ['nombre']

apps/complementos/organigrama/forms.py
from django import forms

from .models import Entidad


class EntidadForm(forms.ModelForm):

    nombre = forms.CharField(required=True)
    valor = forms.CharField(required=True)

    def __init__(self, *args, **kwargs):
        super(EntidadForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():

            field.widget.attrs.update({
                'class': 'form-control has-feedback-right'
            })

    class Meta:
        model = Entidad
        fields = '__all__'

apps/complementos/organigrama/views.py
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic import (ListView, CreateView, UpdateView, DeleteView)

from .forms import EntidadForm
from .models import Entidad
from . import helpers


class EntidadListView(ListView):
    model = Entidad
    paginate_by = 10

    def get_queryset(self):

        query = super(EntidadListView, self).get_queryset()

        # parametro = self.request.GET.get('parametro')
        #
        # print(parametro)
        #
        # if parametro:
        #
        #     query = Entidad.objects.filter(
        #         Q(persona__apellido__icontains=parametro) |
        #         Q(persona__nombre__icontains=parametro) |
        #         Q(persona__numero_documento__icontains=parametro)
        #     )

        return query


class EntidadCreate(CreateView):
    model = Entidad
    form_class = EntidadForm

    def get(self, request, *args, **kwargs):

        form = EntidadForm()

        return render_to_response(
            'organigrama/entidad_form.html', {'form': form},
            context_instance=RequestContext(request))

    def post(self, request, *args, **kwargs):

        form = EntidadForm(self.request.POST, self.request.FILES)

        if form.is_valid():
            # form_entidad = form.save(commit=False)

            if 'imagen' in self.request.FILES:
                self.set_foto(form, (self.request.FILES['imagen']))

            form.save()

            messages.add_message(
                request, messages.SUCCESS, 'ENTIDAD CREADA CON EXITO')

            return HttpResponseRedirect('/entidades/modi/%s' %
                                        str(form.instance.id))

        messages.add_message(
            request, messages.SUCCESS, 'EL FORMULARIO CONTIENE ERRORES')

        return render_to_response(
            'organigrama/entidad_form.html', {'form': form},
            context_instance=RequestContext(request))

    def set_foto(self, entidad, foto):
        '''
        foto.name = helpers.cambiar_nombre_imagen(
            foto.name, int(Persona.objects.latest('id').id) + 1)
        '''

        foto.name = helpers.cambiar_nombre_imagen(
            foto.name, entidad.instance.valor)

        foto = helpers.redimensionar_imagen(entidad.instance.imagen, foto.name)
        # Se envia foto subida y el cambio de nombre, como parametros
        entidad.instance.imagen = foto
        entidad.save()

    def get_success_url(self):
        return self.request.get_full_path()


class EntidadUpdate(UpdateView):
    model = Entidad
    form_class = EntidadForm

    def get(self, request, *args, **kwargs):

        entidad = Entidad.objects.get(pk=kwargs['pk'])
        form = EntidadForm(instance=entidad)

        return render_to_response('organigrama/entidad_form.html',
                                  {'form': form},
                                  context_instance=RequestContext(request))

    def post(self, request, *args, **kwargs):

        entidad = Entidad.objects.get(pk=kwargs['pk'])
        form = EntidadForm(
            self.request.POST, self.request.FILES, instance=entidad)

        if form.is_valid():
            if 'imagen' in self.request.FILES:
                self.set_foto(form, (self.request.FILES['imagen']))

            form.save()

            messages.add_message(
                request, messages.SUCCESS, 'ENTIDAD MODIFICADA CON EXITO')

            return HttpResponseRedirect('/entidades/modi/%s' %
                                        str(form.instance.id))

        messages.add_message(
            request, messages.SUCCESS, 'EL FORMULARIO CONTIENE ERRORES')

        return render_to_response(
            'organigrama/entidad_form.html', {'form': form},
            context_instance=RequestContext(request))

    def set_foto(self, entidad, foto):
        '''
        foto.name = helpers.cambiar_nombre_imagen(
            foto.name, int(Persona.objects.latest('id').id) + 1)
        '''

        foto.name = helpers.cambiar_nombre_imagen(
            foto.name, entidad.instance.valor)
        foto = helpers.redimensionar_imagen(entidad.instance.imagen, foto.name)
        # Se envia foto subida y el cambio de nombre, como parametros
        entidad.instance.imagen = foto
        entidad.save()

    def get_success_url(self):
        return self.request.get_full_path()


class EntidadDelete(DeleteView):
    model = Entidad

    def get_success_url(self):
        return '/entidades/listado/'

templates/organigrama/entidad_confirm_delete.html
{% extends 'arbol_item.html' %}
{% block content %}

    <div class="title_right" style="background-color:#ccc">
        <div class="x_title">
            <a href='/'><strong>INICIO</strong></a> --
            <a href='/entidades/listado'><strong>LISTA DE ENTIDADES</strong></a> --
            <a href='/entidades/modi/{{ entidad.id }}'><strong>DATOS DE LA ENTIDAD</strong></a>
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="row">

        <form method="post"> {% csrf_token %}
        <div class="col-md-12 col-sm-12 col-xs-12 animated fadeInDown">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Entidad - {{ object }}</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="col-sm-12">
                        <h2 class="brief"><i> Está seguro de eliminar la siguiente Entidad?</i></h2>
                        <ul class="list-unstyled">
                            <li> <label>Descripcion</label> : {{ object.nombre }} </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="x_panel">
                <div class="x_content">
                    <div class="col-xs-2"></div>
                    <div class="col-xs-5">
                        <div class="col-xs-3 col-sm-3 emphasis">
                            <a class="btn btn-success btn-xl" href="/entidades/listado/" type="button"> <i class="fa fa-arrow-left"></i> Cancelar</a>
                        </div>
                        <div class="col-xs-3 col-sm-3 emphasis">
                            <button class="btn btn-danger btn-xl" type="submit" ><i class="fa fa-trash"></i> Eliminar </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </form>
    </div>
{% endblock %}

templates/organigrama/entidad_form.html
{% extends 'arbol_item.html' %}

{% block content %}
    <div class="title_right" style="background-color:#ccc">
        <div class="x_title">
            <a href='/'><strong>INICIO</strong></a> --
            <a href='/entidades/listado'><strong>LISTA DE ENTIDADES</strong></a> --
            <strong>DATOS DE LA ENTIDAD</strong>
        </div>
    </div>
    <!-- mensaje -->
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Info:</span>
                    {{ message }}
                </div>
            {% endfor %}
            </ul>
        {% endif %}
        <!-- mensaje -->

    <div class="clearfix"></div>

    <form enctype="multipart/form-data" id="demo-form2" method="post" data-parsley-validate class="form-horizontal form-label-left">{% csrf_token %}
    <div class="row">

        <div class="col-md-9 col-sm-9 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><strong>DATOS ENTIDAD</strong></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <label for="fullname" class="col-md-12 col-sm-12 col-xs-12">Nombre de Entidad</label>
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                {{ form.nombre }}
                                <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                {{ form.nombre.errors }}
                            </div>
                            <label for="fullname" class="col-md-12 col-sm-12 col-xs-12">Valor de Entidad</label>
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                {{ form.valor }}
                                <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                {{ form.valor.errors }}
                            </div>
                        </div>
                        <!-- IMAGEN ENTIDAD -->
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <div align="center">
                                <!--Este es el preview -->
                                <div class="img-preview img-preview-sm">
                                    {% if form.instance.imagen %}
                                        <img id="img_tag" src="/media/tramites_entidades/miniatura/{{ form.instance.imagen }}" class="img-thumbnail" width="150px" height="150px">ss
                                        <br>
                                        Actual: <a href="/media/tramites_entidades/normal/{{ form.instance.imagen }}">{{ form.instance.imagen }}</a>vv
                                        <input id="foto-clear_id" name="foto-clear" type="checkbox" />
                                        <label for="foto-clear_id">Limpiar</label>
                                    {% else %}
                                        <img id="img_tag" src="/media/logo/logoentidad.jpg" class="img-thumbnail" width="150px" height="150px">zz
                                    {% endif %}
                                </div>

                                <!--Este es el boton de upload-->
                                <div class="form-group">
                                    <!--asociamos el for del label a la llamada del script de JS -->
                                    <label title="Subir Imagen" for="id_imagen" class="btn btn-primary">
                                        <div style="display: none"> {{ form.imagen }} </div>
                                        <!-- hacer style="display: none es equivalente a class="hide" "-->
                                        {% if form.instance.imagen %}
                                            Cambiar foto  <i class="fa fa-undo"></i>
                                        {% else %}
                                            Cargar foto  <i class="fa fa-upload"></i>
                                        {% endif %}
                                    </label>
                                </div>
                                {% if form.errors.imagen %}
                                     <strong>
                                           {{ form.errors.imagen }}
                                     </strong>
                                 {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9 col-sm-9 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <br>
                        <br>
                        <input type="button" class="btn btn-primary" onclick="window.location='/entidades/listado/'" value="Cancelar"/>
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </div>
            </div>
        </div>

    </div>

    </form>

    <script>
        $(document).ready(function(){

            $('.errorlist').css('border', '1px solid transparent');
            $('.errorlist').css('border-radius', '4px');
            $('.errorlist').css('color', '#a94442');
            $('.errorlist').css('background', '#f2dede');
            $('.errorlist').css('border-color', '#ebccd1');
            $('.errorlist').css('font-size', '0.9em');
            $('.errorlist').css('list-style-type', 'none');

            function readURL(input) {

                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function(e) {
                        $("#img_tag").attr("src", e.target.result);
                    }

                    reader.readAsDataURL(input.files[0]);
                }
            }

            $('#id_imagen').change(function() {
                readURL(this);
            });

        });


    </script>

{% endblock %}

templates/organigrama/entidad_list.html
{% extends 'arbol_item.html' %}
{% load staticfiles %}


{% block content %}
    <div class="title_right" style="background-color:#ccc">
        <div class="x_title">
            <a href='/'><strong>INICIO</strong></a> --
            <strong>LISTA DE ENTIDADES</strong></a>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">
        <form method="get" id="frm">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">

                <div class="x_content">
                    <div class="x_title">
                        <h2>LISTA DE ENTIDADES</h2>
                        <div style="text-align: right">
                            <button type="button" class="btn btn-primary btn-round" onclick="window.location='/entidades/alta/'"><i class="fa fa-plus"></i> Crear Entidad</button>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    {% for entidad in object_list %}
                        <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="tile-stats" style="padding: 5px;">
                                <div class="count">
                                    {% if entidad.imagen %}
                                         <img src="/media/tramites_entidades/normal/{{ entidad.imagen }}" class="img-rounded" width="182px" height="87px">
                                    {% else %}
                                        <img src="/media/logo/formingdeveloper_icon_grises_75x75.png" class="img-rounded" width="182px" height="87px">
                                    {% endif %}
                                     <div style="text-align: right">
                                        <h4>
                                            <a href="/entidades/modi/{{ entidad.id }}" title="Breve informe"> +Info</a> |
                                            <a href="/entidades/modi/{{ entidad.id }}" title="Editar"><i class="fa fa-pencil"></i></a> |
                                            <a href="/entidades/delete/{{ entidad.id }}" title="Eliminar"><i class="fa fa-trash"></i></a>
                                        </h4>
                                    </div>
                                </div>

                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
        </form>
    </div>

    <script>

        $("#btnBuscar").click(function () {
            $("#frm").submit();
        });

    </script>


{% endblock %}