admincase/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import autenticarse
from django.conf import settings
from admincase import views

urlpatterns = [
    url(r'^$', autenticarse),
    url(r'^autenticar_usuario/', views.autenticar_usuario),
    # url(r'^reset_password/', views.reset_password, name='rest_password'),
    url(r'^ayuda/', views.ayuda),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^clientes/', include('apps.clientes.urls', namespace='clientes')),
    url(r'^contactos/', include('apps.contactos.urls', namespace='contactos')),
    url(r'^domicilios/', include('apps.domicilios.urls',
                                 namespace='domicilios')),
    url(r'^inicio/', views.inicio, name='inicio'),
    url(r'^internos/', views.internos, name='internos'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, }),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),
    url(r'^salir/', views.salir),
    url(r'^tramites/', include('apps.tramites.urls', namespace='tramites')),
    url(r'^entidades/', include('apps.complementos.organigrama.urls',
                                namespace='entidades')),

    url(r'^reset_password/', include('password_reset.urls')),
]

apps/contactos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from .views import ContactoCreate, ContactoDelete, ContactoUpdate


urlpatterns = patterns('',
    url(r'^alta/(?P<pk>[0-9]+)/$',
        ContactoCreate.as_view(), name='contacto_create'),
    url(r'^modi/(?P<pk>[0-9]+)/$',
        ContactoUpdate.as_view(), name='contacto_update'),
    url(r'^delete/(?P<pk>[0-9]+)/$',
        ContactoDelete.as_view(), name='contacto_delete'),
)

apps/contactos/models.py
from django.db import models

from apps.personas.models import Persona


class TipoContacto(models.Model):

    descripcion = models.CharField(max_length=100, null=False, blank=False)
    valor = models.CharField(max_length=100)

    def __str__(self):
        return self.descripcion

    class Meta:
        verbose_name = 'Tipo de contacto'
        verbose_name_plural = 'Tipos de contactos'


class Contacto(models.Model):

    persona = models.ForeignKey(Persona, null=False, blank=False)
    proveedor = models.CharField(max_length=100,
                                 null=True, blank=True)
    tipo_contacto = models.ForeignKey(TipoContacto, null=True, blank=True)
    descripcion = models.CharField(max_length=100, null=False, blank=False)
    observacion = models.TextField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.persona.nombre) + '-' + str(self.persona.apellido) \
               + " - " + self.descripcion

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'

apps/contactos/forms.py
from django import forms
from django.forms.utils import ErrorList

from .models import Contacto, TipoContacto

proveedores = (
    ('', '------'),
    ('Telecom', 'Telecom'),
    ('Personal', 'Personal'),
    ('Movistar', 'Movistar'),
    ('Claro', 'Claro'),
    ('Otro', 'Otro'),
)


class ContactoForm(forms.ModelForm):

    tipo_contacto = forms.ModelChoiceField(
        queryset=TipoContacto.objects.all(), required=True)
    proveedor = forms.ChoiceField(choices=proveedores, required=False)
    descripcion = forms.CharField(required=True)
    observacion = forms.CharField(
        required=False, widget=forms.Textarea(attrs={'rows': 3}))

    def __init__(self, *args, **kwargs):
        super(ContactoForm, self).__init__(*args, **kwargs)

        for name, field in list(self.fields.items()):
            field.widget.attrs.update({'class': 'form-control'})

    # def clean(self):
    #     # print(self.cleaned_data['tipo_contacto'])
    #     # if str(self.cleaned_data['tipo_contacto']) == 'INTERNO':
    #     #                 print('acaaaaa')
    #     #                 print(RegexValidator(r'[0-9]+', self.cleaned_data['descripcion']))
    #     #                 if not re.match(r'[0-9]+', self.cleaned_data['descripcion']):
    #     #                     errors = self._errors.setdefault("descripcion",
    #     #                                                      ErrorList())
    #     #                     errors.append('Ingrese un formato correcto')
    #     if not self.instance.pk:
    #         if 'descripcion' in self.cleaned_data:
    #             if 'tipo_contacto' in self.cleaned_data:
    #                 if Contacto.objects.filter(descripcion=self.cleaned_data['descripcion'],
    #                                            tipo_contacto=self.cleaned_data['tipo_contacto']).exists():
    #                     errors = self._errors.setdefault("descripcion",
    #                                                          ErrorList())
    #                     errors.append('Ya registro este contacto')
    #     return super(ContactoForm, self).clean()

    class Meta:
        model = Contacto
        fields = '__all__'

apps/contactos/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.views.generic import CreateView, DeleteView, UpdateView
from django.shortcuts import render_to_response

from .models import Contacto
from apps.clientes.models import Cliente

from .forms import ContactoForm


class ContactoCreate(SuccessMessageMixin, CreateView):

    model = Contacto
    form_class = ContactoForm

    def get(self, request, *args, **kwargs):

        form = ContactoForm()

        cliente = Cliente.objects.get(pk=kwargs['pk'])

        # contactos_list = Contacto.objects.filter(persona_id=cliente.persona.id)
        contactos_list = cliente.persona.contacto_set.all()

        return render_to_response(
            'contactos/contacto_form.html',
            {
                'form': form,
                'cliente': cliente,
                'contactos_list': contactos_list
            },
            context_instance=RequestContext(request)
        )

    def post(self, request, *args, **kwargs):

        form = ContactoForm(data=self.request.POST)

        cliente = Cliente.objects.get(pk=kwargs['pk'])

        contactos_list = cliente.persona.contacto_set.all()

        if form.is_valid():

            form.save()

            messages.add_message(
                request, messages.SUCCESS,
                'CONTACTO CREADO CON EXITO')

            return HttpResponseRedirect('/contactos/alta/' + str(cliente.id))

        messages.add_message(
            request, messages.SUCCESS, 'EL FORMULARIO CONTIENE ERRORES')

        return render_to_response(
            'contactos/contacto_form.html',
            {
                'form': form,
                'cliente': cliente,
                'contactos_list': contactos_list
            },
            context_instance=RequestContext(request)
        )


class ContactoUpdate(SuccessMessageMixin, UpdateView):

    model = Contacto
    form_class = ContactoForm

    def get(self, request, *args, **kwargs):

        contacto = Contacto.objects.get(pk=kwargs['pk'])

        form = ContactoForm(instance=contacto)

        cliente = contacto.persona.cliente

        contactos_list = contacto.persona.contacto_set.all()

        return render_to_response(
            'contactos/contacto_form.html',
            {
                'form': form,
                'cliente': cliente,
                'contactos_list': contactos_list
            },
            context_instance=RequestContext(request)
        )

    def post(self, request, *args, **kwargs):

        contacto = Contacto.objects.get(pk=kwargs['pk'])

        cliente = contacto.persona.cliente

        form = ContactoForm(self.request.POST, instance=contacto)

        contactos_list = contacto.persona.contacto_set.all()

        if form.is_valid():

            form.save()

            messages.add_message(
                request, messages.SUCCESS, 'CONTACTO MODIFICADO CON EXITO')

            return HttpResponseRedirect('/contactos/alta/' + str(cliente.id))

        messages.add_message(
            request, messages.SUCCESS, 'EL FORMULARIO CONTIENE ERRORES')

        return render_to_response(
            'contactos/contacto_form.html',
            {
                'form': form,
                'cliente': cliente,
                'contactos_list': contactos_list
            },
            context_instance=RequestContext(request)
        )


class ContactoDelete(DeleteView):

    model = Contacto

    def get_success_url(self):
        contacto = Contacto.objects.get(pk=self.kwargs['pk'])

        messages.add_message(
            self.request, messages.SUCCESS, 'EL CONTACTO FUE ELIMINADO CON ÉXITO')

        return '/contactos/alta/' + str(contacto.persona.cliente.id)

templates/contactos/contacto_confirm_delete.html
{% extends 'arbol_item.html' %}
{% block content %}
<form method="post"> {% csrf_token %}
      <div class="col-md-8 col-sm-8 col-xs-12 animated fadeInDown">
            <div class="well profile_view">
                <div class="col-sm-12">
                    <h4 class="brief"><i> Confirma la eliminación del siguiente registro : {{ object.tipo_contacto }}</i></h4>
                    <div class="left col-xs-7">
                        <ul class="list-unstyled">
                            <li> Descripcion : {{ object.descripcion }} </li>
                        </ul>
                        <br>
                        <br>
                    </div>
                </div>
                <div class="col-xs-12 bottom text-center">
                    <div class="col-xs-12 col-sm-6 emphasis">
                         <a class="btn btn-success btn-xl" href="/contactos/alta/{{ request.session.id }}" type="button" ><i class="fa fa-arrow-left"></i>Cancelar</a>
                    </div>
                    <div class="col-xs-12 col-sm-6 emphasis">
                        <button class="btn btn-danger btn-xl" type="submit" ><i class="fa fa-trash">
                            </i>    Eliminar </button>
                    </div>
                </div>
            </div>
        </div>
</form>
{% endblock %}

templates/contactos/contacto_form.html
    {% extends 'arbol_item.html' %}
    {% load staticfiles %}
    {% block content %}

        <div class="title_right" style="background-color:#ccc">
            <div class="x_title">
                <a href='/'><strong>INICIO</strong></a> --
                <a href='/clientes/listado'><strong>LISTA DE CLIENTES</strong></a> --
                <a href='/clientes/modi/{{ cliente.id }}'><strong>DATOS DEL CLIENTE</strong></a> --
                <strong>CONTACTO</strong> --
                <a href='/tramites/listado/{{ cliente.id }}'><strong>HISTORIAL DE TRAMITES</strong></a>
            </div>
        </div>

        <!-- mensaje -->
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Info:</span>
                    {{ message }}
                </div>
            {% endfor %}
            </ul>
        {% endif %}
        <!-- mensaje -->
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Contacto - {{ cliente | title }}</h2>
                        <div class="clearfix"></div>
                    </div>


                    <div class="x_content">
                        <form id="demo-form2" method="post" data-parsley-validate class="form-horizontal form-label-left">{% csrf_token %}
                        <input id="id_persona" name="persona" type="hidden" value="{{ cliente.persona.id }}" />

                        <div class="form-group">
                            <label class="control-label" for="first-name">Tipo de Contacto(*) <span class="required"></span></label>
                            {{ form.tipo_contacto }}
                            {% if form.tipo_contacto.errors %}
                                <div class="alert alert-danger" role="alert">
                                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"> {{ form.tipo_contacto.label }}</span>
                                    {{ form.tipo_contacto.errors }}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-group" id="id_proveedor_div">
                            <label class="control-label" for="first-name">Proveedor <span class="required"></span></label>
                            {{ form.proveedor }}
                            {% if form.proveedor.errors %}
                            <div class="alert alert-danger" role="alert">
                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"> {{ form.proveedor.label }}</span>
                                {{ form.proveedor.errors }}
                            </div>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="first-name">Descripción(*) <span class="required"></span></label>

                            <div class="item form-group">
                             {{ form.descripcion }}
                            </div>
                            <label id="mensaje_formato" class="">Ejemplo : +54-(370) 4xx-xxxxxx </label>
                            {% if form.descripcion.errors %}
                                <div class="alert alert-danger" role="alert">
                                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"> {{ form.descripcion.label }}</span>
                                    {{ form.descripcion.errors }}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="first-name">Observación <span class="required"></span></label>
                            {{ form.observacion }}
                            {% if form.observacion.errors %}
                                <div class="alert alert-danger" role="alert">
                                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"> {{ form.observacion.label }}</span>
                                    {{ form.observacion.errors }}
                                </div>
                            {% endif %}
                        </div>
                        <br>
                        <div class="form-group">
                            <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
                                <a href="/{{ request.session.modulo }}/modi/{{ request.session.id }}" type="button" class="btn btn-primary">Cancelar</a>
                                <button type="submit" class="btn btn-success">Guardar</button>
                            </div>
                        </div>

                        </form>
                    </div>
                </div>
            </div>

            <div class="col-md-8 col-sm-8 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Lista de Contactos</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="example" class="table table-striped responsive-utilities jambo_table">
                            <thead>
                                <tr class="headings">
                                    <th></th>
                                    <th>Tipo</th>
                                    <th>Decripción </th>
                                    <th>Observación </th>
                                    <th class=" no-link last">
                                        <span class="nobr">Editar</span>
                                    </th>
                                    <th class=" no-link last">
                                        <span class="nobr">Eliminar</span>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for contacto in contactos_list %}
                                <tr class="odd pointer">
                                    {% if contacto.tipo_contacto.valor == 'SITIO_WEB' %}
                                        <td class><i class="fa fa-sitemap"></i></td>
                                    {% endif %}

                                    {% if contacto.tipo_contacto.valor == 'EMAIL' %}
                                        <td class><i class="fa fa-envelope"></i></td>
                                    {% endif %}

                                    {% if contacto.tipo_contacto.valor == 'TELEFONO_FIJO' %}
                                        <td class><i class="fa fa-phone-square"></i></td>
                                    {% endif %}

                                    {% if contacto.tipo_contacto.valor == 'LABORAL' %}
                                        <td class><i class="fa fa-phone"></i></td>
                                    {% endif %}

                                    {% if contacto.tipo_contacto.valor == 'TELEFONO_MOVIL' %}
                                        <td class><i class="fa fa-mobile-phone"></i></td>
                                    {% endif %}

                                    <td class=" ">{{ contacto.tipo_contacto }}</td>
                                    <td class=" ">{{ contacto.descripcion }}</td>
                                    <td class=" ">{{ contacto.observacion }}</td>
                                    <td><a href="/contactos/modi/{{contacto.id}}"><i class="fa fa-pencil"></i></a></td>
                                    <td><a href="/contactos/delete/{{contacto.id}}"><i class="fa fa-trash-o"></i></a></td>
                                </tr>
                            {% empty %}
                                <div class="alert alert-danger" role="alert">
                                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                    <span class="sr-only">Error:</span>
                                    No se encontraron registros
                                </div>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- input mask -->
        <script src="{% static 'js/input_mask/jquery.inputmask.js' %}"></script>
        <!-- form validation -->
        <script src="{% static 'js/validator/validator.js' %}"></script>
        <script>
            $( document ).ready(function() {
                $(":input").inputmask();
                document.getElementById('mensaje_formato').style.display = 'none';
                verificar_tipo_contacto();
            });
            $('#id_tipo_contacto').on('change', function() {
                verificar_tipo_contacto();
            });
            var verificar_tipo_contacto = function(){
                var elemento = document.getElementById("id_tipo_contacto");
                var valor = elemento.options[elemento.selectedIndex].text;
                switch(valor) {
                    case 'MÓVIL':
                         $('#id_proveedor').prop("disabled", false);
                         $('#id_descripcion').prop('required',true);
                         $('#id_descripcion').prop("type", "tel");
                         break;
                    case 'INTERNO':
                         document.getElementById('mensaje_formato').style.display = 'none';
                         $('#id_proveedor').prop("disabled", true);
                         $('#id_descripcion').prop('required',true);
                         break;
                    case 'LABORAL':
                         document.getElementById('mensaje_formato').style.display = 'none';
                         $('#id_proveedor').prop("disabled", true);
                         $('#id_descripcion').prop('required',true);
                         $('#id_descripcion').prop("type", "tel");
                         break;
                    case 'PARTICULAR':
                         document.getElementById('mensaje_formato').style.display = 'none';
                         $('#id_proveedor').prop("disabled", true);
                         $('#id_descripcion').prop('required',true);
                         $('#id_descripcion').prop("type", "text");
                         break;
                    case 'E-MAIL':
                         document.getElementById('mensaje_formato').style.display = 'none';
                         $('#id_descripcion').unmask();
                         $('#id_proveedor').prop("disabled", true);
                         $('#id_descripcion').prop('required',true);
                         $('#id_descripcion').prop("type", "email");
                         break;
                    case 'SITIO WEB':
                         document.getElementById('mensaje_formato').innerHTML = "Ejemplo :  http://www.google.com.ar";
                         document.getElementById('mensaje_formato').style.display = 'block';
                         $('#id_descripcion').unmask();
                         $('#id_proveedor').prop("disabled", true);
                         $('#id_descripcion').prop('required',true);
                         $('#id_descripcion').prop("type", "url");
                         break;
                    default:
                         $('#id_descripcion').unmask();
                }
            };

            validator.message['date'] = 'not a real date';
            $('form')
                .on('blur', 'input[required], input.optional, select.required', validator.checkField)
                .on('change', 'select.required', validator.checkField)
                .on('keypress', 'input[required][pattern]', validator.keypress);
            $('.multi.required')
                .on('keyup blur', 'input', function () {
                    validator.checkField.apply($(this).siblings().last()[0]);
                });
            $('form').submit(function (e) {
                e.preventDefault();
                var submit = true;
                if (!validator.checkAll($(this))) {
                    submit = false;
                }
                if (submit)
                    this.submit();
                return false;
            });
            $('#vfields').change(function () {
                $('form').toggleClass('mode2');
            }).prop('checked', false);
            $('#alerts').change(function () {
                validator.defaults.alerts = (this.checked) ? false : true;
                if (this.checked)
                    $('form .alert').remove();
            }).prop('checked', false);

            $( "#id_descripcion" ).keypress(function(evt)
                {
                var elemento = document.getElementById("id_tipo_contacto");
                var valor = elemento.options[elemento.selectedIndex].text;
                if (valor == 'MÓVIL' || valor == 'INTERNO' || valor == 'LABORAL' || valor == 'PARTICULAR'){
                    var charCode = (evt.which) ? evt.which : event.keyCode
                    if (charCode != 43 && charCode > 31 && (charCode < 39 || charCode > 57))
                        return false;
                    return true;
                }
            });
    </script>
{% endblock %}